import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import NextTopLoader from "@/components/ui/next-top-loader";
import { defaultMetadata } from "./metadata";
import { RootProvider } from "@/components/root-provider";
import { Suspense } from "react";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/react"
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  ...defaultMetadata,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className={inter.className}>
            {/* Envolva o NextTopLoader com seu próprio Suspense */}
            <Suspense fallback={null}>
              <NextTopLoader />
            </Suspense>
            <Suspense fallback={null}>
              <RootProvider>
                {children}
                <Toaster />
              </RootProvider>
            </Suspense>
            <SpeedInsights />
            <Analytics />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}