import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import NextTopLoader from "@/components/ui/next-top-loader";
import { defaultMetadata } from "./metadata";
import { RootProvider } from "@/components/root-provider";
import { NotificationPoller } from "@/components/notification-poller";
import { Suspense } from "react";
import { Analytics } from "@vercel/analytics/next"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  ...defaultMetadata,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <NextTopLoader />
        {/* Envolva o RootProvider com Suspense */}
        <Suspense fallback={null}>
          <RootProvider>
            <NotificationPoller />
            {children}
            <Toaster />
          </RootProvider>
        </Suspense>
        <Analytics />
      </body>
    </html>
  );
}